# Generated by Django 2.2.5 on 2019-09-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, verbose_name='Ürün Kodu')),
                ('name', models.CharField(max_length=130, verbose_name='Ürün Adı')),
                ('stock', models.IntegerField(verbose_name='Ürün Adedi')),
                ('price', models.FloatField(verbose_name='Ürün Fiyatı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
